spring:
  application:
    name: fraud-processing-engine
  
  # 👑 FIX: Relocating configuration blocks under Spring's active auto-config prefix
  datasource:
    url: ${DB_URL}
    username: ${DB_USER:postgres}
    password: ${DB_PWD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5         # Protection ceiling against connection leaks
      connection-timeout: 3000     # 3 seconds timeout
      minimum-idle: 2

  # Kafka Consumer Connection Targets
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka-cluster-broker:9042}

# Custom Application Properties
temporal:
  server-address: ${TEMPORAL_SERVER_ADDRESS:temporal-central-server:7233}
  task-queue: "order-saga-queue"

# Observability Lane Metrics Routing
management:
  endpoints:
    web:
      exposure:
        include: "prometheus,metrics,health"
  metrics:
    distribution:
      percentiles-enabled:
        http.server.requests: true
        kafka.listener.stream: true
      percentiles:
        http.server.requests: 0.5, 0.99, 0.999
        kafka.listener.stream: 0.5, 0.99, 0.999
